In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df1 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202007.csv', encoding='utf-16')
df2 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202008.csv', encoding='utf-16')
df3 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202009.csv', encoding='utf-16')
df4 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202010.csv', encoding='utf-16')
df5 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202011.csv', encoding='utf-16')
df6 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202012.csv', encoding='utf-16')
df7 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202101.csv', encoding='utf-16')
df8 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202102.csv', encoding='utf-16')
df9 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202104.csv', encoding='utf-16')
df10 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202105.csv', encoding='utf-16')
df11 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202106.csv', encoding='utf-16')
df12 = pd.read_csv('drive/MyDrive/Dataset Reviews/reviews202107.csv', encoding='utf-16')

all_df = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]
data = pd.concat(all_df, ignore_index=True)
data

In [ ]:
df_reviews = pd.DataFrame(data[['Review Text', 'Star Rating']])
df_reviews

Review Text  Star Rating
0               Great apps. We can learn AI Online now            5
1    Sangat bermanfaat. Bisa belajar online sekaran...            5
2    Aplikasinya bagus dan sangat membantu pembelaj...            5
3    Great app! Has a very friendly user interface ...            5
4    sangat bagus untuk para pemula dan yang mau la...            5
..                                                 ...          ...
266  Cukup bermanfaat dalam pelatihan saya dalam be...            5
267  Easy to use! Aplikasi yang sangat bagus diguna...            5
268                                                NaN            5
269              Aplikasi yang dapat mendukung belajar            5
270  Habis daftar kok nggk bisa login? Katanya suru...            4

[271 rows x 2 columns]

In [ ]:
sentiments = []

for star in data['Star Rating']:
  if star == 1 or star == 2:
    sentiments.extend(['Negatif'])
  elif star == 3:
    sentiments.extend(['Netral'])
  elif star == 4 or star == 5:
    sentiments.extend(['Positif'])

In [ ]:
df_reviews["Sentiment"] = sentiments
df_reviews

Review Text  Star Rating Sentiment
0               Great apps. We can learn AI Online now            5   Positif
1    Sangat bermanfaat. Bisa belajar online sekaran...            5   Positif
2    Aplikasinya bagus dan sangat membantu pembelaj...            5   Positif
3    Great app! Has a very friendly user interface ...            5   Positif
4    sangat bagus untuk para pemula dan yang mau la...            5   Positif
..                                                 ...          ...       ...
266  Cukup bermanfaat dalam pelatihan saya dalam be...            5   Positif
267  Easy to use! Aplikasi yang sangat bagus diguna...            5   Positif
268                                                NaN            5   Positif
269              Aplikasi yang dapat mendukung belajar            5   Positif
270  Habis daftar kok nggk bisa login? Katanya suru...            4   Positif

[271 rows x 3 columns]

In [ ]:
all_stars = df_reviews.groupby('Star Rating')['Star Rating'].count()
all_stars

Star Rating
1      8
2      7
3      5
4     13
5    238
Name: Star Rating, dtype: int64

In [ ]:
all_reviews = df_reviews.groupby('Sentiment')['Sentiment'].count()
all_reviews

Sentiment
Negatif     15
Netral       5
Positif    251
Name: Sentiment, dtype: int64

In [ ]:
df_reviews.to_csv('Hasil_Review.csv', index=False)

In [ ]:
df = pd.read_csv('Hasil_Review.csv')
df

Review Text  Star Rating Sentiment
0               Great apps. We can learn AI Online now            5   Positif
1    Sangat bermanfaat. Bisa belajar online sekaran...            5   Positif
2    Aplikasinya bagus dan sangat membantu pembelaj...            5   Positif
3    Great app! Has a very friendly user interface ...            5   Positif
4    sangat bagus untuk para pemula dan yang mau la...            5   Positif
..                                                 ...          ...       ...
266  Cukup bermanfaat dalam pelatihan saya dalam be...            5   Positif
267  Easy to use! Aplikasi yang sangat bagus diguna...            5   Positif
268                                                NaN            5   Positif
269              Aplikasi yang dapat mendukung belajar            5   Positif
270  Habis daftar kok nggk bisa login? Katanya suru...            4   Positif

[271 rows x 3 columns]

In [ ]:
df.columns = ['Review_Text', 'Star_Rating', 'Sentiment']

In [ ]:
df = df.dropna()
df

Review_Text  Star_Rating Sentiment
0               Great apps. We can learn AI Online now            5   Positif
1    Sangat bermanfaat. Bisa belajar online sekaran...            5   Positif
2    Aplikasinya bagus dan sangat membantu pembelaj...            5   Positif
3    Great app! Has a very friendly user interface ...            5   Positif
4    sangat bagus untuk para pemula dan yang mau la...            5   Positif
..                                                 ...          ...       ...
264                        the app is very easy to use            5   Positif
266  Cukup bermanfaat dalam pelatihan saya dalam be...            5   Positif
267  Easy to use! Aplikasi yang sangat bagus diguna...            5   Positif
269              Aplikasi yang dapat mendukung belajar            5   Positif
270  Habis daftar kok nggk bisa login? Katanya suru...            4   Positif

[206 rows x 3 columns]

In [ ]:
import re
def casefolding(Review_Text):
  Review_Text = Review_Text.lower()
  Review_Text = Review_Text.strip()
  Review_Text = re.sub(r'[,.?!;:/-123(")²]', '', Review_Text)
  return Review_Text
df['Review_Text'] = df['Review_Text'].apply(casefolding)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


Review_Text  Star_Rating Sentiment
0                great apps we can learn ai online now            5   Positif
1    sangat bermanfaat bisa belajar online sekarang...            5   Positif
2    aplikasinya bagus dan sangat membantu pembelaj...            5   Positif
3    great app has a very friendly user interface a...            5   Positif
4    sangat bagus untuk para pemula dan yang mau la...            5   Positif
..                                                 ...          ...       ...
264                        the app is very easy to use            5   Positif
266  cukup bermanfaat dalam pelatihan saya dalam be...            5   Positif
267  easy to use aplikasi yang sangat bagus digunak...            5   Positif
269              aplikasi yang dapat mendukung belajar            5   Positif
270  habis daftar kok nggk bisa login katanya suruh...            4   Positif

[206 rows x 3 columns]

In [ ]:
def token(Review_Text):
  dele = Review_Text.split(' ')
  dat = []
  a = -1
  for hu in dele:
    a += 1
  if hu == '':
    dat.append(a)
  p = 0
  b = 0
  for q in dat:
    b = q - p
    del dele[b]
    p += 1
  return dele
df['Review_Text'] = df['Review_Text'].apply(token)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()


Review_Text  Star_Rating Sentiment
0       [great, apps, we, can, learn, ai, online, now]            5   Positif
1    [sangat, bermanfaat, bisa, belajar, online, se...            5   Positif
2    [aplikasinya, bagus, dan, sangat, membantu, pe...            5   Positif
3    [great, app, has, a, very, friendly, user, int...            5   Positif
4    [sangat, bagus, untuk, para, pemula, dan, yang...            5   Positif
..                                                 ...          ...       ...
264                [the, app, is, very, easy, to, use]            5   Positif
266  [cukup, bermanfaat, dalam, pelatihan, saya, da...            5   Positif
267  [easy, to, use, aplikasi, yang, sangat, bagus,...            5   Positif
269        [aplikasi, yang, dapat, mendukung, belajar]            5   Positif
270  [habis, daftar, kok, nggk, bisa, login, katany...            4   Positif

[206 rows x 3 columns]

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
def stopword_removal(Review_Text):
  filtering = stopwords.words('indonesian', 'english')
  x = []
  d = []
  def func(x):
    if x in filtering:
      return False
    else:
      return True
  fil = filter(func, Review_Text)
  for x in fil:
    d.append(x)
  return d
df['Review_Text'] = df['Review_Text'].apply(stopword_removal)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Review_Text  Star_Rating Sentiment
0       [great, apps, we, can, learn, ai, online, now]            5   Positif
1            [bermanfaat, belajar, online, materi, ai]            5   Positif
2         [aplikasinya, bagus, membantu, pembelajaran]            5   Positif
3    [great, app, has, a, very, friendly, user, int...            5   Positif
4      [bagus, pemula, tahap, expert, aplikasi, mudah]            5   Positif
..                                                 ...          ...       ...
264                [the, app, is, very, easy, to, use]            5   Positif
266           [bermanfaat, pelatihan, belajar, coding]            5   Positif
267          [easy, to, use, aplikasi, bagus, belajar]            5   Positif
269                     [aplikasi, mendukung, belajar]            5   Positif
270  [habis, daftar, nggk, login, suruh, periksa, k...            4   Positif

[206 rows x 3 columns]

In [ ]:
pip install Sastrawi

     |████████████████████████████████| 209 kB 16.4 MB/s 


In [ ]:
import Sastrawi
import sklearn
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory as stmf
from sklearn.pipeline import Pipeline

In [ ]:
def stemming(Review_Text):
  facto = stmf()
  stemmer = facto.create_stemmer()
  e = []
  for i in Review_Text:
    f = stemmer.stem(i)
    e.append(f)
  d_clean = []
  d_clean = ' '.join(e)
  print(d_clean)
  return d_clean
df['Review_Text'] = df['Review_Text'].apply(stemming)

great apps we can learn ai online now
manfaat ajar online materi ai
aplikasi bagus bantu ajar
great app has a very friendly user interface and very easy to use
bagus mula tahap expert aplikasi mudah
bantu ajar teknologi zaman lanjut
mudah paham aplikasi user friendly good job
mantul
aplikasi manfaat media ajar era baru
huhuu platform ajar ai
pilih ajar baik
aplikasi butuh mantap
mantab
aplikasi bantu ajar coursenya gk melulu bayar register free course moga bagus aplikasi depan
great apps
aplikasi tarik benar mudah ajar programming lupa download yah
aplikasi bantu ajar programming ajar tarik serta video silabus lengkap lupa quiz tugas dapat sertifikat coursenya
sukaa iot materi mudah paham next ai
mula sy cocok banget beljar lengkap smua fiturnya
aplikasi mantap coursenya mudah paham
sory klo emang good tambahin lg
good job materi nya mudah paham alangkah baik quis blm code nya suruh output terimakasih
mantap course gratis nya yg android development mudah paham
course nya mantap banget 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [ ]:
df.to_csv('clean.csv', index=False)
clean = pd.read_csv('clean.csv')
clean

In [ ]:
clean = clean.astype({'Sentiment' : 'category'})
clean = clean.astype({'Star_Rating' : 'category'})
clean = clean.astype({'Review_Text' : 'string'})
clean.dtypes

Review_Text      string
Star_Rating    category
Sentiment      category
dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
tf_text = tf.fit_transform(clean['Sentiment'].astype('U'))
tf_text

<206x3 sparse matrix of type '<class 'numpy.float64'>'
	with 206 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(tf_text, df['Sentiment'], test_size=0.2, random_state=22)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
exam = MultinomialNB().fit(x_train, y_train)
pred = exam.predict(x_test)
print('Accuracy : ', accuracy_score(y_test, pred))
print('Precision : ', precision_score(y_test, pred, average='weighted'))
print('Recall : ', recall_score(y_test, pred, average='weighted'))
print('F1 Score : ', f1_score(y_test, pred, average='weighted'))

print(f'Confusion Matrix :\n {confusion_matrix(y_test, pred)}')
print('-------------------------------------------------------\n')
print(classification_report(y_test, pred, zero_division=0))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 Score :  1.0
Confusion Matrix :
 [[ 2  0  0]
 [ 0  2  0]
 [ 0  0 38]]
-------------------------------------------------------

              precision    recall  f1-score   support

     Negatif       1.00      1.00      1.00         2
      Netral       1.00      1.00      1.00         2
     Positif       1.00      1.00      1.00        38

    accuracy                           1.00        42
   macro avg       1.00      1.00      1.00        42
weighted avg       1.00      1.00      1.00        42

